# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Alejo/Downloads/Nexys4DDR_Master.xdc

# IP: ip/clk_12_Meg/clk_12_Meg.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_12_Meg || ORIG_REF_NAME==clk_12_Meg}]
